qcom-cpufreq: Fix build after commit d5aeb18a2306
With COMMON_CLK_MSM disabled, one could have expected this build error:

  /mnt/ssd/kernels/msm-4.9/drivers/cpufreq/qcom-cpufreq.c:450:4: error:
  incomplete definition of type 'struct clk'
                  c->flags |= CLKFLAG_NO_RATE_CACHE;
                  ~^
  /mnt/ssd/kernels/msm-4.9/include/linux/clk.h:21:8: note: forward declaration
  of 'struct clk'
  struct clk;
         ^
  1 error generated.
  make[3]: *** [/mnt/ssd/kernels/msm-4.9/scripts/Makefile.build:339:
  drivers/cpufreq/qcom-cpufreq.o] Error 1
  make[2]: *** [/mnt/ssd/kernels/msm-4.9/scripts/Makefile.build:653:
  drivers/cpufreq] Error 2
  make[2]: *** Waiting for unfinished jobs....
  make[1]: *** [/mnt/ssd/kernels/msm-4.9/Makefile:1121: drivers] Error 2
  make[1]: *** Waiting for unfinished jobs....
  make: *** [Makefile:152: sub-make] Error 2

Make sure CLKFLAG_NO_RATE_CACHE to only be passed if COMMON_CLK_MSM is enabled.

Signed-off-by: Albert I <kras@raphielgang.org>